from mm import M, over
PAL = {'A':('#c7ceda','#7f8898','#454c5a'), 'O':('#ffc49e','#ff8a3d','#a8461a'), 'B':('#4f5462','#30343f','#191b22'),
       'Z':('#9aa1ae','#646b78','#33373f'), 'H':('#fff0d8','#e7c79a','#8c6a3c'), 'K':'#120f12', 'S':('#ffffff','#d2d6de','#7a8090'), 'G':'#ffb347', 'C':'#ff9a86', 'R':'#ff4d4d', 'W':'#ffffff', 'X':'#ffe066'}
FRONT = M([
 "...ZZ.......",
 "..ZZZZ......",
 "..ZZZZ......",
 "..ZZZZ.....H",
 "..ZZZZ...HHA",
 "..ZOOZ.AAAAA",
 "..ZZZZ.AAAAA",
 "..ZZZZ.AKKKK",
 "...ZZ..AKGGG",
 "OOOO...AAAAA",
 "OAAAOO..BBBB",
 "OAAAAOOAAAAA",
 "OAAAAOAAAARR",
 ".OOOOBAAAARR",
 "...BBBBAAAAA",
 "...AA..OOOOO",
 "......BBBBBB",
 "......AAAA..",
 "......AAAA..",
 "......BBBB..",
 ".....OAAAA..",
 ".....OAAAA..",
 ".....OOOOOO.",
 "............",
])
SHIELD = [
 "........................", "........................", "........................", "........................",
 "........................", "........................", "........................", "........................",
 "........................",
 "..................AAAA..",
 ".ZZZZ............AAAAAA.",
 "ZOOOOZ...........AOOOOA.",
 "ZOZZOZ...........AOAAOA.",
 "ZOOOOZ...........AOOOOA.",
 "ZZZZZZ...........AAAAAA.",
 ".BZZB............AAAAAA.",
 "..SS..............AAAA..",
 "..SW...............AA...",
 "..SW....................",
 "..SS....................",
 "...S....................",
 "........................", "........................", "........................",
]
FRONT = over(FRONT, SHIELD)
BACK = M([
 "...ZZ.......",
 "..ZZZZ......",
 "..ZZZZ......",
 "..ZZZZ.....H",
 "..ZZZZ...HHA",
 "..ZZZZZAAAAA",
 "..ZZZZZAAAAA",
 "..ZZZZZAAAAA",
 "...ZZZZZAAAA",
 "OOOO..ZZZZZZ",
 "OAAAOOZZBBBB",
 "OAAAAOZZBBBB",
 "OAAAAOZZBBBB",
 ".OOOOBZXXBBB",
 "...BBBBXXBBB",
 "...AA..OOOOO",
 "......BBBBBB",
 "......AAAA..",
 "......AAAA..",
 "......BBBB..",
 ".....OAAAA..",
 ".....OAAAA..",
 ".....OOOOOO.",
 "............",
])
SIDE = [
 "....ZZZ.................",
 "...ZZZZZ................",
 "...ZZZZZ......H.........",
 "...ZZZZZ.....HHA........",
 "...ZOOZZ..AAAAAAA.......",
 "...ZZZZZ..AAAAAAAA......",
 "...ZZZZZ..AAAAKKKK......",
 "...ZZZZZ..AAAAKGGG......",
 "....XXX...AAAAAAAA......",
 ".....X..OOOO.BBBB.......",
 "........OAAAOOAAAAA.....",
 "........OAAAAOAAAAARR...",
 "........OAAAAOAZZZZZZ...",
 ".........OOOOBZOOOOOZSSS",
 "...........BBBZZZZZZZSWW",
 "............AA.BZZZZBSS.",
 "..............BBBB......",
 "............AAAA.AAAA...",
 "............AAAA.AAAA...",
 "............BBBB.BBBB...",
 "...........OAAAA.OAAAA..",
 "...........OAAAA.OAAAA..",
 "...........OOOOOOOOOOOO.",
 "........................",
]
