def M(rows):
    out=[]
    for r in rows:
        assert len(r)==8, (r,len(r))
        out.append(r + r[::-1])
    return out
S = {}
# 重装：大头盔 + 一字护目镜，巨型肩甲，粗短腿
S['heavy'] = dict(
front = M([
 "....oooo",
 "...oaaaa",
 "..oaaaaa",
 "..obwwww",
 "..obweew",
 "..obdddd",
 "oooodddo",
 "oaaboabb",
 "oabbobcc",
 "odbdobbb",
 ".oooobdd",
 "...oogoo",
 "...obbbo",
 "..oabbdo",
 "..odddoo",
 "..oooo..",
]),
back = M([
 "....oooo",
 "...oaaaa",
 "..oaaaaa",
 "..obaaaa",
 "..obbbbb",
 "..obdddd",
 "oooookkk",
 "oaabokgg",
 "oabbokgl",
 "odbdokrr",
 ".ooooorr",
 "...oogoo",
 "...obbbo",
 "..oabbdo",
 "..odddoo",
 "..oooo..",
]),
side = [
 ".....oooooo.....",
 "....oaaaaaao....",
 "...oaaaaaaaao...",
 "...obbbwwwwwo...",
 "...obbbwweeoo...",
 "...obbddddddo...",
 "..oooooddooo....",
 ".oggooaabbaoo...",
 ".oglgoabcccbaoo.",
 ".oglgobbbbbbbbo.",
 ".okkgoddddoooo..",
 "..ooooogoo......",
 "......obbbo.....",
 ".....oabbbdo....",
 ".....oddddoo....",
 ".....ooooo......",
])
# 近卫：头顶单刃冠，双眼，修长，背后剑柄
S['guard'] = dict(
front = M([
 ".......o",
 "......oa",
 "....oooa",
 "...oaaaa",
 "...obwww",
 "...obeww",
 "...obddd",
 "....oooo",
 "...oaobb",
 "..oabobc",
 "..obdobb",
 "..oo.okd",
 ".....obo",
 "....oabo",
 "....oddo",
 "....ooo.",
]),
back = M([
 ".......o",
 "......oa",
 "....oooa",
 "...oaaaa",
 "...obaaa",
 "...obbbb",
 "...obddd",
 "....oool",
 "...oaobl",
 "..oaborr",
 "..obdokg",
 "..oo.okd",
 ".....obo",
 "....oabo",
 "....oddo",
 "....ooo.",
]),
side = [
 ".......oo.......",
 "......oaao......",
 ".....oaaaao.....",
 "....oaaawwwo....",
 "....obbbweeo....",
 "....obbbwwwo....",
 "....obbddddo....",
 ".....oooooo..ow.",
 "....oabcbao.owo.",
 "...oabbbbboowo..",
 "...obbdbaaoooo..",
 "....ooddoooo....",
 ".....obbo.......",
 "....oabbo.......",
 "....oddddo......",
 ".....oooo.......",
])
# 狙击：大圆镜头单眼（偏一侧），瘦身，超长枪
S['sniper'] = dict(
front = [
 "................",
 "......oooo......",
 ".....oaaaao.....",
 "....oaaaaaaoo...",
 "....obwwwwoyyo..",
 "....obwewwoyeo..",
 "....obddddoyyo..",
 ".....oooooooo...",
 "....oaobcboao...",
 "...oabobbbobao..",
 "...obdoddddodo..",
 "...oo.obbbo.oo..",
 "......ob.bo.....",
 ".....oabooabo...",
 ".....oddoodd o..".replace(' ','.'),
 "......oo..oo....",
],
back = [
 "................",
 "......oooo......",
 ".....oaaaao.....",
 "...ooaaaaaao....",
 "..oyyoaaaaabo...",
 "..oyyobbbbbbo...",
 "..oyyoddddddo...",
 "...oooooooooo...",
 "....oaokkkoao...",
 "...oabogllobao..",
 "...obdorrrodbo..",
 "...oo.obbbo.oo..",
 "......ob.bo.....",
 ".....obaoobao...",
 ".....oddoodd o..".replace(' ','.'),
 "......oo..oo....",
],
side = [
 "................",
 ".....oooo.......",
 "....oaaaaoo.....",
 "...oaaaaoyyo....",
 "...obbwwoyeo....",
 "...obbweoyyo....",
 "...obbddooo.....",
 "....oooooo......",
 "...oabcbooooooo.",
 "..oabbboklllllwo",
 "..obbbbaggkkkoo.",
 "...oddbooooo....",
 "....obbo........",
 "...oabbo........",
 "...oddddo.......",
 "....oooo........",
])
# 敌方杂兵：圆顶头，三点红色眼带，粗炮臂
S['grunt'] = dict(
front = M([
 "........",
 ".....ooo",
 "....oaaa",
 "...oaaaa",
 "...oaaaa",
 "...ookee",
 "...obddd",
 "..ooodoo",
 ".oaboabb",
 ".obbobcc",
 ".ogoobdd",
 ".oko.obo",
 "..o..obo",
 "....oabo",
 "....oddo",
 "....ooo.",
]),
back = M([
 "........",
 ".....ooo",
 "....oaaa",
 "...oaaaa",
 "...oaaaa",
 "...obbbb",
 "...obddd",
 "..oooook",
 ".oabookg",
 ".obboorr",
 ".ogoookd",
 ".oko.obo",
 "..o..obo",
 "....oabo",
 "....oddo",
 "....ooo.",
]),
side = [
 "................",
 "......oooo......",
 ".....oaaaaoo....",
 "....oaaaaaaao...",
 "....oaaaaaaao...",
 "....obbbookeo...",
 "....obbbddddo...",
 ".....oooooooo...",
 "....oabbcbaoooo.",
 "...oabbbbbgkkkko",
 "...obbdbbooooo..",
 "....oddddo......",
 ".....obbo.......",
 "....oabbo.......",
 "....oddddo......",
 ".....oooo.......",
])
